GET https://localhost:7072/produtos HTTP/1.1

###
GET https://localhost:7072/categorias HTTP/1.1

###
GET https://localhost:7072/categorias/produtos HTTP/1.1

###
GET https://localhost:7072/categorias/2 HTTP/1.1

###
POST https://localhost:7072/produtos HTTP/1.1
content-type: application/json

{
    "nome": "Guaraná pó",
    "descricao": "Refresco",
    "preco": 5,
    "imageUrl": "cocacola.jpg",
    "estoque": 12,
    "dataCadastro": "2024-12-18T23:10:48",
    "categoriaId": 1
  }

  ###
  GET https://localhost:7072/produtos/pagination?PageNumber=1&PageSize=3 HTTP/1.1 